# Generated by Django 3.2.7 on 2021-10-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.PositiveBigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('tier', models.PositiveSmallIntegerField(db_index=True)),
                ('ipfs_hash', models.CharField(max_length=64)),
                ('weight', models.PositiveIntegerField()),
                ('ingredients', models.ManyToManyField(related_name='_app_resource_ingredients_+', to='app.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.PositiveBigIntegerField(db_index=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('seller', models.CharField(max_length=64)),
                ('buyer', models.CharField(blank=True, max_length=64, null=True)),
                ('closed', models.BooleanField(db_index=True, default=False)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resource')),
            ],
        ),
    ]
