# Generated by Django 3.2.7 on 2021-11-17 11:59

from django.db import migrations, models
from django.utils import timezone


def forward_func(apps, schema_editor):
    MarketplaceListing = apps.get_model('app', 'MarketplaceListing')
    db_alias = schema_editor.connection.alias
    MarketplaceListing.objects.using(db_alias).filter(closed=True).update(closed_at=timezone.now())


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(forward_func, reverse_func),
    ]
