# Generated by Django 3.2.7 on 2021-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_marketplacelisting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelisting',
            name='price',
            field=models.DecimalField(decimal_places=18, max_digits=128),
        ),
    ]
