# Generated by Django 3.2.7 on 2021-12-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_marketplacelisting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('weight', models.PositiveIntegerField()),
                ('max_tier', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
