# Generated by Django 3.2.7 on 2021-12-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_gamechat_gamechatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamechat',
            name='player0',
        ),
        migrations.RemoveField(
            model_name='gamechat',
            name='player1',
        ),
    ]
