# Generated by Django 3.2.7 on 2022-01-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220102_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.PositiveSmallIntegerField()),
                ('game_id', models.PositiveIntegerField()),
                ('winner', models.CharField(blank=True, max_length=64, null=True)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gameinfo')),
            ],
        ),
    ]
