# Generated by Django 3.2.7 on 2022-01-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_gameinfo_gameplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='game_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='league',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='started',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
