# Generated by Django 4.0.1 on 2022-01-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220117_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.PositiveBigIntegerField(db_index=True)),
                ('price', models.DecimalField(decimal_places=18, max_digits=128)),
                ('duration', models.DurationField()),
                ('lender', models.CharField(max_length=64)),
                ('borrower', models.CharField(blank=True, max_length=64, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('closed', models.BooleanField(db_index=True, default=False)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resource')),
            ],
        ),
    ]
