# Generated by Django 4.0.1 on 2022-01-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_lendinglisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendinglisting',
            name='duration',
            field=models.DurationField(),
        ),
    ]
