# Generated by Django 4.0.1 on 2022-01-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_lendinglisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameleaderboarditem',
            name='_played_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameleaderboarditem',
            name='_wins_offset',
            field=models.IntegerField(default=0),
        ),
    ]
